include: package:flutter_lints/flutter.yaml

# 링크 : https://dart.dev/tools/analysis
analyzer:
  plugins:
    - custom_lint
  exclude: [
    lib/**.g.dart,
    test/**.mocks.dart,
  ] ## ignore, info, warning, error
  errors:
    todo: info

# 링크 : https://dart.dev/tools/linter-rules
linter:
  rules:
    - avoid_print

# 링크 https://pub.dev/documentation/riverpod_lint/latest/#all-the-lints
custom_lint:
  rules:
    - missing_provider_scope: false